### ISSUE TITLE
Not compatible with emacs below 24.4

### ISSUE THREAD

**Issue by JohnLunzer** [alphapapa/outshine#13]
you use the function `with-eval-after-load` which was added in 24.4

You can do a version check and fall back on the previous syntax.

For 24.4 and above you can use what you current use:
```elisp
;; trigger eldoc (elisp help in echo area), like `self-insert-command'
(with-eval-after-load 'eldoc
  (eldoc-add-command 'outshine-self-insert-command))
```
below that use:
```elisp
;; trigger eldoc (elisp help in echo area), like `self-insert-command'
(eval-after-load 'eldoc
  '(progn
     (eldoc-add-command 'outshine-self-insert-command)))
```
As far as I can tell this is the only incompatibility with emacs 24 below 24.4. For the record I am using 24.3.1.

**Comment by alphapapa** [comment]
Hi John,

Well, since `with-eval-after-load` is a macro, if we were going to make a change, it would probably be best to just use the latter form rather than a version check.  However, 24.3 is now five years old, and I'm reluctant to make any changes to support such old Emacs versions.  I'm sure you have a reason, but may I ask why you're using that version?

**Comment by JohnLunzer** [comment]
There is a critical mass of technological infrastructure which is frozen in time. The reasons vary: lack of time/funding to upgrade, bureaucratic restrictions, lack of permissions, hesitancy to "mess with perfectly working" legacy systems, etc. Some industries/sectors feel these things more than others.

I will not hound you to make this change. However, I feel that it is in the best interest of outshine to do so. I would only say: we should all strive for the greatest compatibility with the least amount of trouble (time/upkeep/complexity). This change will give outshine better compatibility with near-insignificant trouble.

I would not downgrade the entire package to `eval-after-load`; the newer `with-eval-after-load` was added for a reason. I recommend the fallback strategy using a version check. If you put in a comment  `;; with-eval-after-load added in v24.4` it should not overcomplicate the code.

**Comment by alphapapa** [comment]
Yes, I know that enterprise-type stuff moves slowly, old RHEL/CentOS versions, etc, but even so, five years is unusually old as far as I know.  I've had people ask for 24.4 or 24.5 compatibility, but you're the first to ask for 24.3.  I'm reluctant to make such a change for such old software for a single user, at least in the master branch.  I wouldn't mind pushing a branch for 24.3, without any guarantees of support.  Of course, it wouldn't be in MELPA, but you could install it by other means.  Would that help?

**Comment by JohnLunzer** [comment]
That seems like much more trouble than a one time change that has no
negative consequences. In the interest of keeping the repo clean I will
just patch it myself on a forked version.

For the record I did not propose the change for myself, I've already worked
around it. My goal was to improve the universal compatibility of a very
important package. I can only guarantee you that there are plenty of people
using old software, enough to write software to work for them too,
especially if that means adding a few lines of code.

**Comment by alphapapa** [comment]
Yes, I myself am using Ubuntu 14.04 on one system, which is now 4 years old, so I empathize.  I have had to upgrade some software, including Emacs, manually.  I don't like breaking backward compatibility without good reason.  But you're asking me to *add* support for a version of Emacs that isn't currently supported, is over 5 years old, was released well before I assumed maintenance of the project, and you're the only user who's asked for it.  And Emacs 26 is just around the corner.  I'm sorry, but in this case, I don't think the change is justified.  There are many other Emacs packages, with orders of magnitude more users, who don't even support versions as old as Outshine currently does.  I think I have to draw the line somewhere, because my time is limited.

If you are interested in posting your fork online, I'd be happy to link to it in the readme with a note about earlier versions of Emacs, in case other users might find it useful.
