### ISSUE TITLE
package-autoremove wants to remove outshine

### ISSUE THREAD

**Issue by notuntoward** [alphapapa/outshine#25]
After I update and install the latest emacs packages, emacs has started asking me every time if I want to remove an unused package.  If I type M-x package-autoremove, emacs tells me that it will delete outshine.  But actually am using outshine and I don't want to remove it because I like it.

It looks like outshine is somehow not registering itself in a way that emacs (26.1) recognizes.

In addition, package-autoremove wants to delete the outorg package, which is an outshine dependency.

Here's my outshine configuration in .emacs:

(use-package outshine
  :diminish outline-mode
  :diminish outline-minor-mode
  :config
  (add-hook 'outline-minor-mode-hook 'outshine-hook-function) ; for outshine
  (add-hook 'prog-mode-hook 'outline-minor-mode)              ; all prog modes
  ;; from https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-outshine.el
  (bind-keys
   :map outline-minor-mode-map
   ("<backtab>" . outshine-cycle-buffer)))

**Comment by alphapapa** [comment]
Please try removing and reinstalling the package.

**Comment by notuntoward** [comment]
I let package-autoremove do it, and then I reinstalled and did it myself.
But after that, package-autoremove was still not satisfied, and continued
to want to remove outshine and outorg.

**Comment by alphapapa** [comment]
Can you reproduce the problem in a clean Emacs config?

**Comment by severen** [comment]
I'm not so sure this is an issue with Outshine. I've had this issue with many other packages in the past when I used package.el + use-package. Your issue is probably that Outshine is not being put in the `user-selected-packages` variable (see [here](http://endlessparentheses.com/new-in-package-el-in-emacs-25-1-user-selected-packages.html) for info), and so Emacs thinks it's okay to remove it. Whether this a package.el or use-package issue, I'm not so sure, although I'm leaning towards use-package.
