### ISSUE TITLE
Broken Folding

### ISSUE THREAD

**Issue by dustinlacewell** [alphapapa/outshine#47]
@alphapapa asked that this video be uploaded as reference during refactoring the cycling code. It demonstrates a dead heading that wont cycle.

https://i.imgur.com/pL2rurh.mp4

**Comment by yuhan0** [comment]
I can't reproduce this behavior on the current master branch and the file: https://github.com/dustinlacewell/sutysisku.el/blob/master/sutysisku.el

@dustinlacewell What is the value of `outline-regexp` in that buffer? It might be due to other minor modes on that affect outlines - `lispy` in particular configures things in an opinionated way that aren't compatible with Outshine at the moment.

**Comment by thblt** [comment]
Maybe related: I suspect that outshine often breaks `imenu`, in a way I haven't yet been able to determine.  The list of symbols is built correctly but trying to jump to a given symbol brings me in an unrelated (albeit constant) location in the file, usually near the top.
